# Generated by Django 4.1.3 on 2022-11-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flightid', models.AutoField(db_column='FlightId', primary_key=True, serialize=False)),
                ('date', models.TextField(blank=True, db_column='Date', null=True)),
                ('days', models.IntegerField(blank=True, db_column='Days', null=True)),
                ('flightnum', models.IntegerField(blank=True, db_column='FlightNum', null=True)),
                ('aircraftid', models.TextField(blank=True, db_column='AircraftId', null=True)),
                ('from_field', models.TextField(blank=True, db_column='From', null=True)),
                ('to', models.TextField(blank=True, db_column='To', null=True)),
                ('out', models.IntegerField(blank=True, db_column='Out', null=True)),
                ('off', models.IntegerField(blank=True, db_column='Off', null=True)),
                ('on', models.IntegerField(blank=True, db_column='On', null=True)),
                ('in_field', models.IntegerField(blank=True, db_column='In', null=True)),
                ('total', models.FloatField(blank=True, db_column='TOTAL', null=True)),
                ('night', models.FloatField(blank=True, db_column='Night', null=True)),
                ('imc', models.FloatField(blank=True, db_column='IMC', null=True)),
                ('pilotflying', models.IntegerField(blank=True, db_column='PilotFlying', null=True)),
                ('approachtype', models.TextField(blank=True, db_column='ApproachType', null=True)),
                ('dayt_o', models.IntegerField(blank=True, db_column='DayT/O', null=True)),
                ('dayldg', models.IntegerField(blank=True, db_column='DayLdg', null=True)),
                ('nightt_o', models.IntegerField(blank=True, db_column='NightT/O', null=True)),
                ('nightldg', models.IntegerField(blank=True, db_column='NightLdg', null=True)),
                ('remarks', models.TextField(blank=True, db_column='Remarks', null=True)),
            ],
            options={
                'db_table': 'Flight',
                'managed': False,
            },
        ),
    ]
